const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const worker = fs.readFileSync(path.join(__dirname, "..", "src", "index.ts"), "utf8");
const client = fs.readFileSync(path.join(__dirname, "..", "public", "game.js"), "utf8");
const page = fs.readFileSync(path.join(__dirname, "..", "public", "index.html"), "utf8");
const styles = fs.readFileSync(path.join(__dirname, "..", "public", "styles.css"), "utf8");
const rules = fs.readFileSync(path.join(__dirname, "..", "public", "rules.html"), "utf8");
const config = fs.readFileSync(path.join(__dirname, "..", "wrangler.jsonc"), "utf8");

assert.match(config, /"class_name": "GameRoom"/, "GameRoom Durable Object binding is required");
assert.match(config, /"directory": "\.\/public"/, "static client must be bundled with the Worker");
assert.match(worker, /ctx\.storage\.put\("room"/, "the authoritative room state must be persisted server-side");
assert.match(worker, /this\.ctx\.acceptWebSocket/, "room updates must use Durable Object WebSockets");
assert.match(worker, /player\.hand = player\.hand\.filter/, "discard mutations must occur on the server");
assert.match(worker, /D6_DISCARD_FACES = \[0, 1, 1, 2, 2, 3\]/, "the discard die must have the approved six faces");
assert.match(worker, /const faceIndex = randomInt\(6\)/, "mandatory D6 rolls must be generated server-side");
assert.match(worker, /room\.phase = "discussion"/, "every round must enter a server-authoritative discussion phase");
assert.match(worker, /this\.ctx\.storage\.setAlarm\(room\.discussionEndsAt\)/, "discussion end must use a Durable Object alarm");
assert.match(worker, /async alarm\(\): Promise<void>/, "the Durable Object must resume the game after discussion");
assert.match(worker, /type === "CHAT"/, "discussion chat messages must be validated server-side");
assert.match(worker, /type === "SKIP_DISCUSSION"/, "discussion skip votes must be validated server-side");
assert.match(worker, /room\.discussionVotes\.length === room\.players\.length/, "discussion can only skip after every player agrees");
assert.match(worker, /deck\.splice\(0, room\.playerTarget \* 2\)/, "two cards per player must be removed before dealing");
assert.match(worker, /room\.removed = deck\.splice/, "removed cards must be retained for king-condition accounting");
assert.match(worker, /deployedKingCount <= 9 && \(baseline\.handCounts\.king \|\| 0\) === 0/, "a low-count king set must leave no king in any final hand");
assert.match(worker, /const allDiscard = room\.players\.flatMap\(\(player\) => \[\.\.\.player\.publicDiscard, \.\.\.player\.finalDiscard\]\)/, "the full grave must include public and final-round private discards");
assert.match(worker, /case "king": success = \(baseline\.discardCounts\.king \|\| 0\) >= 9/, "king's normal condition must use the full grave");
assert.match(worker, /case "noble": success = baseline\.finalByPlayer\.flat\(\)\.filter\(\(card\) => card\.type === "noble"\)\.length === 3/, "noble must count every final-round private discard, not only its owner's");
assert.match(worker, /case "jester": \{ const guesses = room\.players\.find\(\(candidate\) => candidate\.role === "assassin"\)\?\.action\.assassin as Array<\{ player: number; role: RoleKey \}> \| undefined; success = !!guesses\?\.some\(\(guess\) => guess\.player === player\.index && guess\.role !== "jester"\); break; \}/, "jester must succeed only when the assassin points at them with a non-jester role");
assert.match(worker, /case "knight": success = \(baseline\.discardCounts\.knight \|\| 0\) === minDiscard/, "knight must compare full-grave counts");
assert.match(worker, /case "pope": success = \(baseline\.discardCounts\.pope \|\| 0\) >= 6/, "pope must count the full grave");
assert.match(worker, /finalDiscard\.push/, "fourth-round discards must be stored separately");
assert.match(worker, /viewFor\(sessionId/, "the server must create a per-player filtered view");
assert.match(worker, /Math\.abs\(total\) > 1/, "role selection must enforce a total card score of 0 or ±1");
assert.match(worker, /room\.hostId !== sessionId/, "only the host may change the role set or start the game");
assert.match(worker, /requestedSwaps\.length > 2/, "mercenary exchanges must be capped at two cards");
assert.match(worker, /swap\.graveOwner\.publicDiscard/, "mercenary must take cards from the shared public grave");
assert.match(worker, /player\.publicDiscard\.push\(swap\.own\)/, "mercenary's exchanged-out card must return to the public grave");
assert.doesNotMatch(worker, /hand: player\.hand, publicDiscard: player\.publicDiscard[\s\S]*role: room\.phase/, "public player views must not expose another player's hand");
assert.match(client, /WebSocket\(/, "client must connect to the room with WebSocket");
assert.match(client, /renderDiscussion\(\)/, "client must render the discussion stage");
assert.match(client, /playDiceRoll\(/, "client must animate shared dice rolls");
assert.match(client, /discussion-skip/, "client must expose the discussion skip control");
assert.match(page, /공개 무덤 확인/, "public discard access must remain visible");
assert.match(page, /rules\.html/, "the game header must link to the rules help page");
assert.match(styles, /Pretendard|role-mosaic-atlas/, "the online client must retain the visual card system");
assert.match(styles, /card-rule-slot-v1\.png/, "card rule text must use the readable illustrated slot");
assert.match(styles, /d6-tumble/, "the shared D6 must have a roll animation");
assert.ok(fs.existsSync(path.join(__dirname, "..", "public", "assets", "card-rule-slot-v1.png")), "the illustrated card rule slot asset must be bundled");
assert.match(rules, /직업별 성공 조건/, "rules help must explain every role condition");
assert.match(rules, /용병의 교환/, "rules help must explain the shared public-grave exchange");
assert.match(rules, /라운드 종료 토론/, "rules help must explain the discussion phase");
assert.match(rules, /0·1·1·2·2·3/, "rules help must document the D6 faces");
assert.match(rules, /전원이 동의하면/, "rules help must explain unanimous discussion skip");
console.log("online.rules.static: PASS");
